name: v12.6.0-custom

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - run: git clone https://github.com/alexsch01/test GitHubActionsRoot
        working-directory: C:\
        
      - name: Build
        run: |
          docker run `
            --rm `
            --entrypoint powershell.exe `
            --memory 8GB `
            -v C:\GitHubActionsRoot:C:\GitHubActionsRoot `
            -w C:\GitHubActionsRoot `
          mcr.microsoft.com/windows/server:ltsc2022 {
            .\v12.6.0-custom.cmd
          }
        working-directory: C:\GitHubActionsRoot

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: v12.6.0-custom
          path: C:\GitHubActionsRoot\cypress.zip
